sudo: required
dist: trusty
language: c++
services:
- docker
before_script:
- docker pull monolit/sdk
script:
- docker run --env APP_DIR=/monoapp --volume `pwd`:/monoapp monolit/sdk
notifications:
  slack:
    on_success: change
    secure: CtvnFuoGwwDOi/ShrSov34K9FXl2kBuZ9aQ13iWmkK3UZV0nvK2KbCXYCj6MkNFXGnhlQZVAyU9JOb0+A+3sQMHVeshS4fFTCq5iRn8/p2SQIKVAkIt982Txpju/+jaB3L7WgQ0LV104r6/fofLYl2DSj1tcNomWpu1bQnZSnySBuijhNLmrR3HCTCyE2Gk7oXPwkdYtbEXC2yS5AOqE8IcZMul5qEMAhqXe3tEPnfTyW5BMwKNmD6ZINjULZgZ66aXdtL28hzW61ky/deQKlM4GqrMTZ23wOYbyungBlsKB2L12zBccHm0Vu340L9XVgNqfos1TlwxTNgpPVc4qQeYEUGCxgNguNHsl62wByAXJh8ZCgIhXYh2MOZgcY8Q7zq+XSB3eSUHQ8wg9FExuxChUx+503WZpnYNEUeqPGbAHRaLIcjjITZQz6XUvnjRwHTLTuUeSxM2Thb6gpIRB4Y1W4kgacWNbSdDYr97NknuzIBBbOh9soy3Sblu9cRhYb8wz8uXO/BjrGD5gWZKVgmNBxiu3/1wzmI8eQNewCSPJZ0FLwKgiao28F5JNg5I3pOaysqH4+zwYFobGhtrQudoxYMunyWpxV+66pPlN+BHSHz7C7HVvOJMI8C6NAoY0ubBbBVqqOIHzpieHEWPeQM38NPRG0PZdGHfVDTROlOw=
